workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint
  - pyright
  - build
  - test
  - security-scan
  - export-sbom
  - docs

.git_config: &git_config
# For internal git dependencies
- git config --global url."https://gitlab-ci-token:${PRIVATE_TOKEN}@gitlab.jatic.net".insteadof "ssh://git@gitlab.jatic.net"
- git config --global url."https://gitlab-ci-token:${PRIVATE_TOKEN}@gitlab.jatic.net/".insteadOf "git@gitlab.jatic.net:"
# Need git LFS for pulling MORSE test stage test data
- apt-get update && apt-get install -y git-lfs
- git lfs install

.python-matrix:
  parallel:
    matrix:
      - VERSION: ["3.9", "3.10", "3.11"]
  image: python:$VERSION

.shared-setup:
  interruptible: true
  allow_failure: false
  rules:
    # If changes are make to an active merge request.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    # If changes are pushed to the default branch.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never  # explicit fail-exclude terminal condition.
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"
    ARTIFACT_DIR: "artifacts"  # must match test.artifacts.path below
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
    - .cache
    policy: pull

.conda-setup:
  before_script:
    - *git_config
    - curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
    - eval "$(./bin/micromamba shell hook -s posix)"
    - micromamba create -f environment-optional.yml -n test-env python=$VERSION
    - micromamba activate test-env
    - pip install . --no-deps
    - micromamba list

.poetry-setup:
  before_script:
    - *git_config
    - export PATH=${HOME}/.local/bin:${PATH}
    - pip install --upgrade pip
    - pip install --user -U poetry
    - apt-get update && apt-get install -y openjdk-17-jre
    - poetry config --local virtualenvs.in-project true
    - poetry config --local virtualenvs.prefer-active-python true
    - poetry config repositories.gradient https://gitlab.jatic.net/jatic/morse/gradient.git
    - poetry config repositories.reallabel https://gitlab.jatic.net/jatic/morse/reallabel.git
    - poetry config repositories.survivor https://gitlab.jatic.net/jatic/morse/survivor.git
    - poetry config http-basic.gradient x-token-auth ${PRIVATE_TOKEN}
    - poetry config http-basic.reallabel x-token-auth ${PRIVATE_TOKEN}
    - poetry config http-basic.survivor x-token-auth ${PRIVATE_TOKEN}
    - python --version
    - pip --version
    - poetry --version
    - poetry check

test:
  extends: [.python-matrix, .shared-setup, .poetry-setup]
  stage: test
  needs: []
  script:
    - git lfs pull
    - poetry install --with dev
    - poetry run python src/jatic_ri/object_detection/_panel/configurations/heart_app.py --ci
    - poetry run python src/jatic_ri/object_detection/_panel/configurations/nrtk_app.py --ci
    - poetry run python src/jatic_ri/object_detection/_panel/configurations/reallabel_app.py --ci
    - poetry run python src/jatic_ri/object_detection/_panel/configurations/survivor_app.py --ci
    - poetry run python src/jatic_ri/object_detection/_panel/configurations/xaitk_app.py --ci
    - poetry run pytest tests -vvv --cov=jatic_ri --cov-report term-missing --cov-report xml:coverage_report.xml --cov-fail-under=90
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage_report.xml
    paths:
      - artifacts/*

conda-test:
  extends: [.python-matrix, .shared-setup, .conda-setup]
  stage: test
  needs: []
  script:
    - pytest tests -vvv --cov=jatic_ri --cov-report term-missing --cov-report xml:coverage_report.xml

lint:
  extends: .shared-setup
  image: python:3.10
  stage: lint
  needs: []
  before_script:
    - pip install pre-commit
  script:
    - pre-commit install
    - pre-commit run --all-files --verbose

pyright-internal:
  extends: [.shared-setup, .poetry-setup]
  image: python:3.10
  stage: pyright
  needs: []
  script:
    - poetry install --with dev
    - poetry run pyright src/

# DOCUMENTATION
# deploy docs for merge requests
pages-branch:
  extends: [.shared-setup, .poetry-setup]
  image: python:3.9
  stage: docs
  artifacts:
      expose_as: 'Documentation Build'
      paths:
        - public/
  environment:
      name: docs-preview/$CI_MERGE_REQUEST_IID
      url: "https://jatic.pages.jatic.net/-/reference-implementation/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
      auto_stop_in: 1 week
  script:
    - poetry install --with docs
    - poetry run mkdocs build -d public --no-directory-urls
  variables:
      PUBLIC_URL: "/-/reference-implementation/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/"
  rules:
    # If changes are make to an active merge request.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    # Don't run this rule if on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never

# deploy production docs on merge with main
pages: # this must be named "pages" to get GitLab to run "pages:deploy"
  extends: [.shared-setup, .poetry-setup]
  image: python:3.9
  stage: docs
  script:
    - poetry install --with docs
    - poetry run mkdocs build -d public --no-directory-urls
  artifacts:
    paths:
    - public
  rules:
    # Only run this rule if on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


# SECURITY STAGES
include:
- template: Jobs/SAST.gitlab-ci.yml
- template: Jobs/Dependency-Scanning.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml

clam-av:
  stage: security-scan
  needs: []
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/clamav/clamav:latest
  script:
    # update virus definitions
    - freshclam
    # run virus scan
    - clamscan -r . --infected --scan-archive=yes --log virus-scan.txt
    # determine if there are any infected files
    - NUM_INFECTED_FILES=$(awk '{if(/Infected files:/) print $3}' < virus-scan.txt)
    - status=$([ "$NUM_INFECTED_FILES" -gt 0 ] && echo 1 || echo 0)
    - exit $status
  artifacts:
    when: always
    paths:
      - virus-scan.txt

semgrep-sast:
  stage: security-scan
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

gemnasium-python-dependency_scanning:
  stage: security-scan
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

secret_detection:
  stage: security-scan
  needs: []
  rules:
    - when: always

# EXPORT-SBOM STAGE
# NOTE: This job requires the completion of all dependency scanning
# jobs before executing in order to merge them for export.
export-merged-sbom:
  stage: export-sbom
  image: docker:stable
  rules:
    # Only run this rule if on main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add --update jq curl
  script:
    - >
      curl --header "Authorization: Bearer $PRIVATE_TOKEN"
      --output export.sh --url "https://gitlab.jatic.net/api/v4/snippets/7/raw"
    - /bin/sh export.sh
  artifacts:
    paths:
      - "gl-sbom-merged-*.cdx.json"
