# conda environment requirements
channels:
- conda-forge
- fastai
dependencies:
# jatic-ri
- maite>=0.6.0
- dataeval>=0.69.2
- pytorch=2.1.2
- tensorflow=2.15.0  # required to avoid 2.15.1 which is unavailable for nebari
- tensorflow-datasets=4.8.3
- torchmetrics=1.4.0
- matplotlib=3.8.4
- tensorflow-probability=0.23.0
- nrtk>=0.12.0
- opencv-python-headless=4.9.0.80
- openjdk=17.0.9  # pin required
- pip
- pip:
  - reallabel @ git+https://gitlab-ci-token:${PRIVATE_TOKEN}@gitlab.jatic.net/jatic/morse/reallabel.git@0.4.2
  - survivor @ git+https://gitlab-ci-token:${PRIVATE_TOKEN}@gitlab.jatic.net/jatic/morse/survivor.git@0.1.3
# test
- pytest  # TODO: sort out dev/test deps properly
- pytest-cov
# linting and formatting
- pre-commit
- pyright
# docs
- mkdocs
