site_name: JATIC Reference Implementation
nav:  # navigation links on sidebar
  - Home: index.md
  - Conventions: conventions.md
  - About: about.md
  - Community:
    - Development Strategies: community/development.md
    - Contributing: community/contributing.md
  - Examples:
    - Torchvision Wrapper: examples/torchvision_wrapper.ipynb
    - Dataset Analysis Configuration: examples/dataset_evaluation_configuration.ipynb
    - Image Classification Dataset Wrapper: examples/image_classification_dataset_wrapper.ipynb
  - Object Detection:
    - Models: object-detection/models.md
  - Image Classification:
    - Datasets: image-classification/datasets.md
theme: readthedocs
markdown_extensions:
  - admonition  # enables callout boxes
plugins:
    - mkdocs-jupyter
