site_name: checkmaite
site_url: https://jatic.pages.jatic.net/reference-implementation/reference-implementation/
use_directory_urls: false
theme:
  name: material
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: indigo

nav:  # navigation links on sidebar
  - Home: index.md
  - Get started:
    - get-started/index.md
    - Setup: get-started/install_setup.md
    - Run `checkmaite` interactively: get-started/checkmaite_interactive.md
    - Object Detection Workflow via API: get-started/checkmaite_api_od.ipynb
    - Image Classification Workflow via API: get-started/checkmaite_api_ic.ipynb
    - Remote Inference with Ray Serve: get-started/checkmaite_ray_serve.ipynb
  - Using JATIC tools:
    - tool-usage/index.md
    - Dataset evaluation:
      - Dataeval - Bias: tool-usage/dataeval_bias_tutorial.ipynb
      - Dataeval - Feasibility: tool-usage/dataeval_feasibility_tutorial.ipynb
      - Dataeval - Linting: tool-usage/dataeval_linting_tutorial.ipynb
      - Dataeval - Shift: tool-usage/dataeval_shift_tutorial.ipynb
    - Model evaluation:
      - NRTK: tool-usage/nrtk_tutorial.ipynb
      - XAITK: tool-usage/xaitk_tutorial.ipynb
    - Results & analysis:
      - Analytics Store: tool-usage/analytics_store_tutorial.ipynb

  - Reference:
    - reference/index.md
    - Conventions: reference/conventions.md
    - Analytics Store: reference/analytics_store_guide.ipynb
    - Personas: reference/personas.md
    - Workflows: reference/workflows.md
  - Checkmaite development:
    - development/index.md
    - Development setup: development/dev_setup.md
    - Development strategy: development/dev_strategy.md
    - Key concepts: development/key_concepts.md
    - User persona: development/persona.md
    - Plugin system: development/plugins.md
    - Contributing: development/contributing.md
markdown_extensions:
  - admonition  # enables callout boxes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:  # enables mermaid diagrams in markdown
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocs-jupyter:
      execute: true
      kernel_name: python3
      allow_errors: false
  - search

exclude_docs: |
  reference/examples
  get-started/temp_yolo_dataset
  get-started/tscache
  tool-usage/report
  *_Report.md
